name: Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo check --workspace
      - run: cargo test --workspace
      - run: cargo clippy --workspace